spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hivernate.type: trace
    org.springframework.transaction.interceptor: trace
